baseurl = "https://miun173.github.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Fahmi Irfan"
title = "A Blog"
disqusShortname = "https-fahmifan-github-io"
disablefancyfonts = true
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Miun173 personal blog"
logofile = "logo.png"
faviconfile = "logo.ico"
highlightjs = true
progressively = true
align_left = false
latestpostcount = 5
best = true
lang = "en"
github = "miun173"
email = "fahmifan173@gmail.com"
linkedin = "fahmifan"
twitter = "miun173"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false
disqusShortname = "miun173-github-io"

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"