baseurl = "https://fahmifan.github.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Fahmi Irfan"
title = "fahmifan's blog"
disqusshortname = "fahmifan"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Fahmifan personal blog"
logofile = "img/logo.png"
faviconfile = "img/logo.ico"
highlightjs = true
progressively = true
align_left = false
latestpostcount = 5
best = true
lang = "en"
github = "fahmifan"
email = "fahmifan909@gmail.com"
linkedin = "fahmifan"
twitter = "fahmifan909"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false